sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: ${oss.endpoint}
    access-key-id: ${oss.access-key-id}
    access-key-secret: ${oss.secret}
    bucket-name: ${oss.bucket-name}